repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: stable
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: stable
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://gitlab.com/pycqa/flake8
    rev: stable
    hooks:
    - id: flake8
